version: '3'

services:
  alist:
    image: ghcr.io/monlor/xiaoya-alist
    volumes:
      - xiaoya:/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    environment:
      - TZ=Asia/Shanghai
      - ALIYUN_TOKEN=
      - ALIYUN_OPEN_TOKEN=
      - ALIYUN_FOLDER_ID=
      - AUTO_UPDATE_ENABLED=true
      - AUTO_CLEAR_ENABLED=true
    restart: unless-stopped
    networks:
      - default
  metadata:
    image: ghcr.io/monlor/xiaoya-metadata
    environment:
      - LANG=C.UTF-8
      # - ALIST_ADDR=http://alist:5678
      - EMBY_ENABLED=false
      - JELLYFIN_ENABLED=true
      - AUTO_UPDATE_EMBY_CONFIG_ENABLED=true
    volumes:
      - xiaoya:/etc/xiaoya
      - media:/media/xiaoya
      - config:/media/config
      - meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  jellyfin:
    image: ghcr.io/monlor/xiaoya-jellyfin
    environment:
      - TZ=Asia/Shanghai
      # ALIST_ADDR=http://alist:5678
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - metadata
      - alist
    volumes:
      - media:/media
      - config:/config
      - cache:/cache
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
  media:
  config:
  meta:
  cache: