name: Build and Push Multi-Architecture Docker Images

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'install.sh'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        # This is used to complete the identity challenge
        # with sigstore/fulcio when running outside of PRs.
        id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version and tags
        id: vars
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/xiaoya-alist"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "TAGS=${IMAGE}:latest,${IMAGE}:${VERSION}" >> $GITHUB_ENV
          else
            echo "TAGS=${IMAGE}:latest" >> $GITHUB_ENV
          fi

      - name: Build and push xiaoya-alist
        uses: docker/build-push-action@v4
        with:
          context: ./alist
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push xiaoya-glue
        uses: docker/build-push-action@v4
        with:
          context: ./glue
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push xiaoya-emby
        uses: docker/build-push-action@v4
        with:
          context: ./emby
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push xiaoya-jellyfin
        uses: docker/build-push-action@v4
        with:
          context: ./jellyfin
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
            
      - name: Build and push xiaoya-resilio
        uses: docker/build-push-action@v4
        with:
          context: ./resilio
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
            